### ISSUE TITLE
资源冲突

### ISSUE THREAD

**Issue by rongdongliu** [BaronZ88/ModularizationProject#5]
Error:Execution failed for task ':NewHouseModule:processDebugManifest'.
> Manifest merger failed : Attribute application@label value=(@string/new_house_app_name) from AndroidManifest.xml:8:9-51
	is also present at [com.github.BaronZ88:Retrofit2-FastJson-Converter:1.2] AndroidManifest.xml:13:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:5:5-20:19 to override.

**Comment by rongdongliu** [comment]
```
android.net.Uri.getQueryParameter(java.lang.String)' on a null object reference
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2342)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:154)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5296)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getQueryParameter(java.lang.String)' on a null object reference
                                                       at com.baronzhang.android.newhouse.NewHouseMainActivity_RouterInjecting.<init>(NewHouseMainActivity_RouterInjecting.java:9)
                                                       at java.lang.reflect.Constructor.newInstance(Native Method)
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                       at com.baronzhang.android.router.RouterInjector.createInjecting(RouterInjector.java:32)
                                                       at com.baronzhang.android.router.RouterInjector.inject(RouterInjector.java:20)
                                                       at com.baronzhang.android.newhouse.NewHouseMainActivity.onCreate(NewHouseMainActivity.java:25)
                                                       at android.app.Activity.performCreate(Activity.java:6039)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:154) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:135) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5296) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707) 

```
